DROP TABLE IF EXISTS EMPRUNT;
DROP TABLE IF EXISTS AUTEUR_DE;
DROP TABLE IF EXISTS AUTEUR;
DROP TABLE IF EXISTS USAGER;
DROP TABLE IF EXISTS LIVRE;

CREATE TABLE USAGER(
nom VARCHAR(90) NOT NULL,
prenom VARCHAR(90) NOT NULL,
adresse VARCHAR(300) NOT NULL,
cp VARCHAR(5) NOT NULL,
ville VARCHAR(60) NOT NULL,
email VARCHAR(60) NOT NULL,
code_barre CHAR(15),
PRIMARY KEY (code_barre));

CREATE TABLE LIVRE(
titre VARCHAR(300) NOT NULL,
editeur VARCHAR(90) NOT NULL,
annee INT NOT NULL,
isbn CHAR(14),
PRIMARY KEY (isbn));

CREATE TABLE AUTEUR
(id_auteur INTEGER,
nom VARCHAR(90) NOT NULL,
prenom VARCHAR(90) NOT NULL,
PRIMARY KEY(id_auteur AUTOINCREMENT));

CREATE TABLE AUTEUR_DE
(id_auteur INT,
isbn CHAR(14),
FOREIGN KEY (id_auteur) REFERENCES AUTEUR(id_auteur),
FOREIGN KEY (isbn) REFERENCES LIVRE(isbn));

CREATE TABLE EMPRUNT
(code_barre CHAR(15),
isbn CHAR(14),
retour DATE NOT NULL,
FOREIGN KEY (code_barre) REFERENCES USAGER(code_barre),
FOREIGN KEY (isbn) REFERENCES LIVRE(isbn),
PRIMARY KEY (isbn));
